version: '2'

volumes:
  data-volume:
  api-aspnet-mysql-data:
    driver: local

services:
  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: api-aspnet-mysql
    volumes:
      - api-aspnet-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=api-aspnet
      - MYSQL_DATABASE=api-aspnet
      - MYSQL_USER=api-aspnet
      - MYSQL_PASSWORD=api-aspnet